services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    ports:
      - "15672:15672"
    networks:
      - backend

  user-service:
    build: ./user-service
    # không override entrypoint ở đây, Docker sẽ dùng ENTRYPOINT từ Dockerfile
    env_file:
      - .env
      - ./user-service/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
    volumes:
      - ./docs/user:/app/docs

  patient-service:
    build: ./patient-service
    # cũng không cần override entrypoint ở đây
    env_file:
      - .env
      - ./patient-service/.env
    ports:
      - "8001:8001"
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
    volumes:
      - ./docs/patient:/app/docs

  appointment-service:
    build: ./appointment-service
    env_file:
      - .env
      - ./appointment-service/.env
    ports:
      - "8002:8002"
    depends_on:
      - db
      - rabbitmq
      - user-service
      - patient-service
    networks:
      - backend
    volumes:
      - ./docs/appointment:/app/docs

  doctor-service:
    build: ./doctor-service
    env_file:
      - .env
      - ./doctor-service/.env
    ports:
      - "8003:8003"
    depends_on:
      - db
      - rabbitmq
      - user-service
    networks:
      - backend
    volumes:
      - ./docs/doctor:/app/docs

  notification-service:
    build: ./notification-service
    env_file:
      - .env
      - ./notification-service/.env
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
    # nếu có API, expose port
    ports:
      - "8004:8004"
  

  prescription-service:
    build: ./prescription-service
    env_file:
      - .env
      - ./prescription-service/.env
    ports:
      - "8005:8005"
    depends_on:
      - db
      - rabbitmq
      - user-service    # Thêm dependency này vì prescription có thể cần thông tin user
      - patient-service # Thêm dependency này vì prescription liên quan đến bệnh nhân
      - doctor-service  # Thêm dependency này vì prescription liên quan đến bác sĩ
    networks:
      - backend
    volumes:
      - ./docs/prescription:/app/docs

  pharmacy-service:
    build: ./pharmacy-service
    env_file:
      - .env
      - ./pharmacy-service/.env
    ports:
      - "8006:8006"
    depends_on:
      - db
      - rabbitmq
      - user-service
      - patient-service
      - doctor-service
      - prescription-service
    networks:
      - backend
    volumes:
      - ./docs/pharmacy:/app/docs



  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user-service
      - patient-service
      - prescription-service  # Thêm dependency này
      - pharmacy-service
      - appointment-service
      - doctor-service
      - notification-service
      
    networks:
      - backend

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend


volumes:
  db_data:

networks:
  backend:
