openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/prescriptions/:
    get:
      operationId: v1_prescriptions_list
      tags:
      - v1
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prescription'
          description: ''
    post:
      operationId: v1_prescriptions_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prescription'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Prescription'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Prescription'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prescription'
          description: ''
  /api/v1/prescriptions/{id}/:
    get:
      operationId: v1_prescriptions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this prescription.
        required: true
      tags:
      - v1
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prescription'
          description: ''
    put:
      operationId: v1_prescriptions_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this prescription.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prescription'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Prescription'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Prescription'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prescription'
          description: ''
    patch:
      operationId: v1_prescriptions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this prescription.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPrescription'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPrescription'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPrescription'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prescription'
          description: ''
    delete:
      operationId: v1_prescriptions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this prescription.
        required: true
      tags:
      - v1
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedPrescription:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        appointment_id:
          type: integer
          maximum: 2147483647
          minimum: 0
        patient_id:
          type: integer
          maximum: 2147483647
          minimum: 0
        doctor_id:
          type: integer
          maximum: 2147483647
          minimum: 0
        issued_at:
          type: string
          format: date-time
          readOnly: true
        notes:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/PrescriptionItem'
    Prescription:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        appointment_id:
          type: integer
          maximum: 2147483647
          minimum: 0
        patient_id:
          type: integer
          maximum: 2147483647
          minimum: 0
        doctor_id:
          type: integer
          maximum: 2147483647
          minimum: 0
        issued_at:
          type: string
          format: date-time
          readOnly: true
        notes:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/PrescriptionItem'
      required:
      - appointment_id
      - doctor_id
      - id
      - issued_at
      - items
      - patient_id
    PrescriptionItem:
      type: object
      properties:
        medication:
          type: string
          maxLength: 255
        dosage:
          type: string
          maxLength: 100
        duration_days:
          type: integer
          maximum: 2147483647
          minimum: 0
      required:
      - dosage
      - duration_days
      - medication
