# Generated by Django 5.0.2 on 2025-05-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="user_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID của User bên User Service",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(),
        ),
    ]
